### PR TITLE
Use current loan policy to evaluate renewability

### LINKED ISSUE #961: [mylibrary/prod] FolioClient::IlsError: Renew request for user_id: 2ce1a5eb-8fe4-4487-acd5-5e8ea6901bf6, item_id: 816a1fe2-3661-570d-a1b7-30ff67110a77 was not successful. status: 422, {
  "errors" : [ {
    "message" : "loan at maximum renewal number",
    "parameters" : [ {
      "key" : "loanPolicyName",
      "value" : "1yearfixed-2renew-7daygrace"
    }, {
      "key" : "loanPolicyId",
      "value" : "ad47ac4d-8305-4039-8ac4-93a69a789074"
    } ],
    "overridableBlock" : {
      "name" : "renewalBl...
## Backtrace

    line 256 of [PROJECT_ROOT]/app/services/folio_client.rb: check_response
    line 113 of [PROJECT_ROOT]/app/services/folio_client.rb: renew_item_request
    line 89 of [PROJECT_ROOT]/app/services/folio_client.rb: renew_item

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/62116/faults/100509416)

### PR DESCRIPTION
**Pull request by corylown**
Fixes #961 

Example of record where loan policy has changed since checkout:

In prod:
Screenshot 2023-10-13 at 4 26 29 PM

With these changes:
Screenshot 2023-10-13 at 4 26 23 PM

### CODE REVIEW

File: app/models/folio/patron.rb [hunk 1]
```diff
@@ -258,5 +258,11 @@ def crypt
         ActiveSupport::MessageEncryptor.new(key)
       end
     end
+
+    def patron_type_id
+      # FOLIO's patronGroup refers to the patron type, e.g. Undergraduate, Graduate, Faculty, etc.
```
Comment (jcoyne) [inline app/models/folio/patron.rb:263]: Thanks for adding documentation like this. 👍

**Review by jcoyne — APPROVED** [review]
